### ISSUE TITLE
App crashes when opening either JoinMeeting or StartMeeting

### ISSUE THREAD

**Issue by mahmutaktas** [mieszko4/react-native-zoom-us#51]
Hi,
Our app crashes when we try to open **JoinMeeting** or **StartMeeting**. We used your screen in the **[react-native-zoom-us-test](https://github.com/mieszko4/react-native-zoom-us-test)**. It is working perfectly on its own. But when we try to integrate the package with our current project it crashes. SDK initializes successfully and the alerts are working if the meeting params are invalid. It only crashes when its about to connect the meeting and open meeting screen or waiting screen. We have found that there is a conflict with `react-navigation` package. Since its using a stack structure, opening a window causes the app crashing without throwing an error or anything.

### How to reproduce
Just add the `react-navigation` and `react-navigation-stack` packages to the **[react-native-zoom-us-test](https://github.com/mieszko4/react-native-zoom-us-test)** without changing anything. 
Then enter valid params for meeting. 
Press the either Start Meeting or Join Meeting button.

![crash](https://user-images.githubusercontent.com/44228511/103347170-4b677f80-4aa7-11eb-94c5-32e67bb82c39.PNG)

### Versions
    react: 16.13.1
    react-native: 0.63.3
    react-native-zoom-us: 5.3.4
    react-navigation: 4.4.3
    react-navigation-stack: 2.10.1

**Comment by mahmutaktas** [comment]
We fixed the issue. It turns out we have installed the react-navigation and react-navigation-stack two times. Once we uninstalled the newer version of these, the problem got fixed. The versions we uninstalled are:
    @react-navigation/native: 5.8.10,
    @react-navigation/stack: 5.12.7
Since we are using the older versions, we uninstalled the newer versions. Newer versions may not have the problem at all on their own.

**Comment by mieszko4** [comment]
Thnx @mahmutaktas

**Comment by ajengrf** [comment]
Hi, @mahmutaktas @mieszko4  my app also crash when joining the meeting. I use the latest version of react-navigation and start a new project but it still wont work on android (it is working on iOS). This is the version of packages that I use: 
"@react-navigation/native": "^5.8.10",
"@react-navigation/stack": "^5.12.8",
"react-native-zoom-us": "^5.3.4"

Please I need your support, thanks

**Comment by Savan-ITDEV** [comment]
Hi Guys I'm trying to join a meeting but I got an error and close my app this case is just for Android only and I. don't see any error, did we have any solution for this issue? Thank you for supporting
my version of React Native: "0.70.5",
Lib:  "react-native-zoom-us": "^6.16.5"

**Comment by mieszko4** [comment]
Hopefully will be resolved with https://github.com/mieszko4/react-native-zoom-us/issues/280
